# Generated by Django 6.0.3 on 2026-05-04 22:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_sitecontent_social_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.FileField(blank=True, upload_to='destinations/', validators=[api.models.validate_uploaded_image]),
        ),
        migrations.AlterField(
            model_name='destinationgalleryimage',
            name='image',
            field=models.FileField(blank=True, upload_to='destination-galleries/', validators=[api.models.validate_uploaded_image]),
        ),
        migrations.AlterField(
            model_name='memory',
            name='image',
            field=models.FileField(blank=True, upload_to='memories/', validators=[api.models.validate_uploaded_image]),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='hero_image',
            field=models.FileField(blank=True, upload_to='site/hero/', validators=[api.models.validate_uploaded_image]),
        ),
    ]
